builtin_interfaces/Time stamp

float32 kl30_protected_voltage # Voltage of the KL30 protected circuit(V)
float32 kl30_2_protected_voltage # Voltage of the KL30_2 protected circuit(V)

float32 gatevcu_5v8_fb_voltage # Voltage of the 5V8 feedback circuit(V)
float32 gatevcu_5v_fb_voltage # Voltage of the 5V feedback circuit(V)
 
float32 gatevcu_5v_supply_voltage_0 # Voltage of the 5V supply circuit 0(V)
float32 gatevcu_5v_supply_voltage_1 # Voltage of the 5V supply circuit 1(V)
float32 gatevcu_5v_supply_voltage_2 # Voltage of the 5V supply circuit 2(V)
float32 gatevcu_5v_supply_voltage_3 # Voltage of the 5V supply circuit 3(V)
float32 gatevcu_5v_supply_voltage_4 # Voltage of the 5V supply circuit 4(V)
