builtin_interfaces/Time stamp

uint8 steering_intervention # 0: no intervention, 1: steering intervention
uint8 brake_intervention # 0: no intervention, 1: brake intervention
uint8 acc_pedal_intervention # 0: no intervention, 1: acc pedal intervention
uint8 steer_module_status
uint8 brake_module_status
uint8 gear_module_status
uint8 steer_disconnected
uint8 str_001
uint8 str_002
uint8 str_003
uint8 bm_001
uint8 bm_002
uint8 bm_003
uint8 bm_004
uint8 gm_001
uint8 gm_002
uint8 gm_003
uint8 driver_brake
float32 throttle # throttle value
uint8 brake # brake value
float32 esp_brake_pressure # brake pressure value(Bar)
uint8 steer_module_fb_current
uint8 brake_module_1_fb_current
uint8 brake_module_2_fb_current
uint8 gear_module_fb_current