builtin_interfaces/Time stamp

uint8 steering_intervention # 0: no intervention, 1: steering intervention
uint8 brake_intervention # 0: no intervention, 1: brake intervention
uint8 acc_pedal_intervention # 0: no intervention, 1: acc pedal intervention
float32 throttle # throttle value
uint8 brake # brake value
float32 esp_brake_pressure # brake pressure value(Bar)
uint8 driver_brake # 0:driver not press the brake pedal 1:driver press the brake pedal