builtin_interfaces/Time stamp

float32 ch1_consumption     # Ah
float32 ch2_consumption     # Ah
float32 ch3_consumption     # Ah    
float32 ch4_consumption     # Ah
float32 ch5_consumption     # Ah
float32 ch6_consumption     # Ah
float32 ch7_consumption     # Ah
float32 ch8_consumption     # Ah
float32 ch9_consumption     # Ah
float32 ch10_consumption    # Ah     
float32 ch11_consumption    # Ah
float32 ch12_consumption    # Ah
